{
    'name': " Odoo Mt Okr",
    'author': "MidOcean Technologies",
    'category': "OKR",
    'summary': """ OKR """,
    'website': 'www.midocean.tech',
    'description': """OKR.""",
    'version': '14.0.1.0',
    'icon_image': ['static/description/banner.png'],
    'depends': ['base'],
    'data': ['security/ir.model.access.csv',
             # 'security/okr_security.xml',
             'views/objective_view.xml',
             'views/timesheet_view.xml',
             'views/key_result_view.xml',
             'views/okr_status_view.xml',
             'views/reports_view.xml',
             'views/objective_report_view.xml',
             ],

    'installable': True,
    'application': True,
    'auto_install': False,
}
